name: Docker Build and Run

on:
  push:
    branches:
      - main  # Customize the branch name as needed

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t my-docker-image .

      # Run the Docker container
      - name: Run Docker container
        run: docker run my-docker-image
